title: Laia Campoy
logo: "Laia_color.png"
description: Turning complexity into visual narratives that connect data with people.
theme: jekyll-theme-minimal 
plugins:
  - jekyll-seo-tag # Add SEO plugin
