title: Laia Campoy
logo: "Laia_color.png"
description: Specialized in data visualization and presentation design. I combine years of leading technical and creative teams with strong visual craft to transform complex data into clear, compelling presentations and reports that support decision-making.
plugins:
  - jekyll-seo-tag # Add SEO plugin
