title: Laia Campoy
logo: "Laia_color.png"
description: Specialized in data analysis and data visualization, with a foundation in design and several years leading technical and creative teams. I bring a cross-functional perspective that combines analytical rigor with clear communication and visual thinking.

theme: jekyll-theme-minimal 
plugins:
  - jekyll-seo-tag # Add SEO plugin
