title: Laia Campoy
logo: "Laia_color.png"
description: Turning data, design, and narrative into clarity, insight and meaningful action for teams and organizations.
theme: jekyll-theme-minimal 
plugins:
  - jekyll-seo-tag # Add SEO plugin
